### ISSUE TITLE
Getting "too many requests" error from dropbox when downloading data

### ISSUE THREAD

**Issue by catapan** [guoday/Tencent2019_Preliminary_Rank1st#1]
```
-> wget https://www.dropbox.com/s/x2scxmk8q0p0xae/algo.qq.com_641013010_testa.zip
--2019-07-17 14:07:11--  https://www.dropbox.com/s/x2scxmk8q0p0xae/algo.qq.com_641013010_testa.zip
Resolving www.dropbox.com (www.dropbox.com)... 2620:100:601a:1::a27d:701, 162.125.7.1
Connecting to www.dropbox.com (www.dropbox.com)|2620:100:601a:1::a27d:701|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /s/raw/x2scxmk8q0p0xae/algo.qq.com_641013010_testa.zip [following]
--2019-07-17 14:07:11--  https://www.dropbox.com/s/raw/x2scxmk8q0p0xae/algo.qq.com_641013010_testa.zip
Reusing existing connection to [www.dropbox.com]:443.
HTTP request sent, awaiting response... 429 Too Many Requests
2019-07-17 14:07:11 ERROR 429: Too Many Requests.
```
Can you provide a different location to download the data? Thanks.

**Comment by guoday** [comment]
I have changes another way to download data. Please kindly find it in the readme.
Thanks

**Comment by guoday** [comment]
> -> wget https://www.dropbox.com/s/x2scxmk8q0p0xae/algo.qq.com_641013010_testa.zip
> --2019-07-17 14:07:11--  https://www.dropbox.com/s/x2scxmk8q0p0xae/algo.qq.com_641013010_testa.zip
> Resolving www.dropbox.com (www.dropbox.com)... 2620:100:601a:1::a27d:701, 162.125.7.1
> Connecting to www.dropbox.com (www.dropbox.com)|2620:100:601a:1::a27d:701|:443... connected.
> HTTP request sent, awaiting response... 301 Moved Permanently
> Location: /s/raw/x2scxmk8q0p0xae/algo.qq.com_641013010_testa.zip [following]
> --2019-07-17 14:07:11--  https://www.dropbox.com/s/raw/x2scxmk8q0p0xae/algo.qq.com_641013010_testa.zip
> Reusing existing connection to [www.dropbox.com]:443.
> HTTP request sent, awaiting response... 429 Too Many Requests
> 2019-07-17 14:07:11 ERROR 429: Too Many Requests.
> 
> Can you provide a different location to download the data? Thanks.

I have changes another way to download data. Please kindly find it in the readme.
Thanks
