### ISSUE TITLE
why emb_inp_v2 =  tf.concat(emb_inp_v2,1)? in CIN

### ISSUE THREAD

**Issue by caowencai** [guoday/Tencent2019_Preliminary_Rank1st#2]
https://github.com/guoday/Tencent2019_Preliminary_Rank1st/blob/9fa1544fa14add283ec9abb9a297076f3a0e424f/models/CIN.py#L65

**Comment by guoday** [comment]
Concat cross and multi features in order to feed them into CIN.

**Comment by caowencai** [comment]
> Concat cross and multi features in order to feed them into CIN.

Get it. 
It turns that the misunderstanding of tf.concat  where the parameter means axis instead of value.
Oops~
