### ISSUE TITLE
请问一下运行train.py这个文件时为啥cpu一直打满，gpu利用率1%~3%左右？

### ISSUE THREAD

**Issue by Outstandingwinner** [guoday/Tencent2019_Preliminary_Rank1st#5]

**Comment by Outstandingwinner** [comment]
![gpu2](https://user-images.githubusercontent.com/35617821/91189679-51c6a300-e725-11ea-8dca-6646d74f882f.jpg)
电脑win10，内存64G，1张1080ti跑了几个epcho都是这样，cpu利用率99%，gpu利用率1%左右，请问这样是正常的吗？

**Comment by TomJackson1205** [comment]
你用nvidia-smi看GPU是否调用上，cpu满没什么问题的
